/*
 * File: app/view/PnlCamera.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Camera.view.PnlCamera', {
    extend: 'Ext.Panel',
    alias: 'widget.pnlCamera',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.DataView',
        'Ext.XTemplate'
    ],

    config: {
        fullscreen: true,
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                itemId: 'toolbarTop',
                ui: 'light',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'btnFoto',
                        ui: 'round',
                        text: 'Foto'
                    },
                    {
                        xtype: 'button',
                        itemId: 'btnMedia',
                        text: 'Biblioteca'
                    }
                ]
            },
            {
                xtype: 'dataview',
                itemTpl: [
                    '<div class="thumb"><img src="{url}"></div>'
                ],
                store: 'FotoStore'
            }
        ]
    }

});